name: Build and Release Electron App

on:
  release:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Build and Release Electron App
      uses: electron-userland/electron-builder-action@v2
      with:
        platform: win
        publish: always
        artifact-name: '${productName}-${version}-${os}-${arch}.${ext}'
